// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | JobListSlice
  | TextSectionSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre SEO de la page
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description SEO de la page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Job → Tags*
 */
export interface JobDocumentDataTagsItem {
  /**
   * Tag field in *Job → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: React, Node.js, etc.
   * - **API ID Path**: job.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Content for Job documents
 */
interface JobDocumentData {
  /**
   * Title field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre du poste
   * - **API ID Path**: job.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Company field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nom de l'entreprise
   * - **API ID Path**: job.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Location field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ville ou remote
   * - **API ID Path**: job.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Contract Type field in *Job*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Type de contrat
   * - **API ID Path**: job.contract_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contract_type: prismic.SelectField<
    "CDI" | "CDD" | "Freelance" | "Stage" | "Alternance"
  >;

  /**
   * Salary field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Fourchette de salaire (ex: 45-55k€)
   * - **API ID Path**: job.salary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  salary: prismic.KeyTextField;

  /**
   * Tags field in *Job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<JobDocumentDataTagsItem>>;

  /**
   * Short Description field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description courte pour les listes
   * - **API ID Path**: job.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;

  /**
   * Description field in *Job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description complète du poste
   * - **API ID Path**: job.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Published Date field in *Job*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  published_date: prismic.DateField; /**
   * Meta Title field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre SEO
   * - **API ID Path**: job.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description SEO
   * - **API ID Path**: job.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Job document from Prismic
 *
 * - **API ID**: `job`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<JobDocumentData>, "job", Lang>;

/**
 * Item in *job → Tags*
 */
export interface JobsDocumentDataTagsItem {
  /**
   * Tag field in *job → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Content for job documents
 */
interface JobsDocumentData {
  /**
   * Title field in *job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Company field in *job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Location field in *job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   *  Contract Type field in *job*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.contract_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contract_type: prismic.SelectField<
    "CDD" | "CDI" | "Freelance" | "Stage" | "Alternance"
  >;

  /**
   * Salary field in *job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.salary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  salary: prismic.KeyTextField;

  /**
   * Tags field in *job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<JobsDocumentDataTagsItem>>;

  /**
   * Short Description field in *job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;

  /**
   * Description field in *job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Published Date field in *job*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: jobs.published_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  published_date: prismic.DateField;
}

/**
 * job document from Prismic
 *
 * - **API ID**: `jobs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<JobsDocumentData>, "jobs", Lang>;

export type AllDocumentTypes = HomepageDocument | JobDocument | JobsDocument;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre principal du hero
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sous-titre ou description
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Hero Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * CTA Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texte du bouton
   * - **API ID Path**: hero_section.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  cta_link: prismic.ContentRelationshipField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with title, subtitle, image and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: Hero section avec titre, sous-titre, image et CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *JobList → Default → Primary*
 */
export interface JobListSliceDefaultPrimary {
  /**
   * Section Title field in *JobList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre de la section (ex: Nos offres)
   * - **API ID Path**: job_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *JobList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description optionnelle
   * - **API ID Path**: job_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Jobs field in *JobList → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: job_list.default.primary.jobs
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  jobs: prismic.ContentRelationshipField<"job">;

  /**
   * PostDate field in *JobList → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: 01/01/2002
   * - **API ID Path**: job_list.default.primary.postdate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  postdate: prismic.DateField;
}

/**
 * Default variation for JobList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with title and job relations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobList*
 */
type JobListSliceVariation = JobListSliceDefault;

/**
 * JobList Shared Slice
 *
 * - **API ID**: `job_list`
 * - **Description**: Section liste des offres d'emploi
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobListSlice = prismic.SharedSlice<
  "job_list",
  JobListSliceVariation
>;

/**
 * Item in *JobSlices → Default → Primary → Tech*
 */
export interface JobSlicesSliceDefaultPrimaryTechItem {
  /**
   * Technologia field in *JobSlices → Default → Primary → Tech*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Pole Emplois
   * - **API ID Path**: job_slices.default.primary.tech[].technologia
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technologia: prismic.KeyTextField;
}

/**
 * Primary content in *JobSlices → Default → Primary*
 */
export interface JobSlicesSliceDefaultPrimary {
  /**
   * Title field in *JobSlices → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Job Title
   * - **API ID Path**: job_slices.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Desc field in *JobSlices → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description Jobs
   * - **API ID Path**: job_slices.default.primary.desc
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  desc: prismic.KeyTextField;

  /**
   * PostDate field in *JobSlices → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: 01/01/2000
   * - **API ID Path**: job_slices.default.primary.postdate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  postdate: prismic.DateField;

  /**
   * Tech field in *JobSlices → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_slices.default.primary.tech[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tech: prismic.GroupField<Simplify<JobSlicesSliceDefaultPrimaryTechItem>>;
}

/**
 * Default variation for JobSlices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobSlicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobSlicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobSlices*
 */
type JobSlicesSliceVariation = JobSlicesSliceDefault;

/**
 * JobSlices Shared Slice
 *
 * - **API ID**: `job_slices`
 * - **Description**: JobSlices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobSlicesSlice = prismic.SharedSlice<
  "job_slices",
  JobSlicesSliceVariation
>;

/**
 * Primary content in *TextSection → Default → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
  /**
   * Content field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contenu de la section
   * - **API ID Path**: text_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with rich text content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextSection*
 */
type TextSectionSliceVariation = TextSectionSliceDefault;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: Section de contenu texte riche
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSlice = prismic.SharedSlice<
  "text_section",
  TextSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      JobDocument,
      JobDocumentData,
      JobDocumentDataTagsItem,
      JobsDocument,
      JobsDocumentData,
      JobsDocumentDataTagsItem,
      AllDocumentTypes,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      JobListSlice,
      JobListSliceDefaultPrimary,
      JobListSliceVariation,
      JobListSliceDefault,
      JobSlicesSlice,
      JobSlicesSliceDefaultPrimaryTechItem,
      JobSlicesSliceDefaultPrimary,
      JobSlicesSliceVariation,
      JobSlicesSliceDefault,
      TextSectionSlice,
      TextSectionSliceDefaultPrimary,
      TextSectionSliceVariation,
      TextSectionSliceDefault,
    };
  }
}
